# Generated by Django 2.2.7 on 2019-11-08 14:14

import desecapi.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('desecapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=desecapi.models.uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
